sudo: required

language: cpp
services:
  - docker

before_install:
  # archlinux

  # appimagetool
  - wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O appimagetool.AppImage

script:
  # archlinux
  - docker build . -f deploydocker/Dockerfile.PCSX2-deploy.archlinux -t PCSX2-appimage.archlinux

after_success:
  - mkdir apps

  # archlinux
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti PCSX2-appimage.archlinux cp PCSX2-i386_x86_64-archlinux.AppImage /tmp/apps
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti PCSX2-appimage.archlinux cp PCSX2-i386_x86_64-archlinux.AppImage.zsync /tmp/apps

  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh apps/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always